package cr.ac.una.resourcemanager.view;

import javax.swing.*;

public class View {
    private JTabbedPane tabbedPane1;
    private JPanel panel1;
    private JLabel BusquedaLabel;
    private JTextField IDTFBusq;
    private JTextField NombreTFBusq;
    private JButton buscarButton;
    private JButton imprimirButton;
    private JTextField IDTF;
    private JTextField NombreTF;
    private JTextField TelefonoTF;
    private JButton guardarButton;
    private JButton borrarButton;
    private JButton limpiarButton;
    private JLabel IDBusqueda;
    private JLabel NombreBusqueda;
    private JLabel FuncionarioLabel;
    private JLabel ID;
    private JLabel Nombre;
    private JLabel Telefono;
    private JLabel ListadoLabel;
    private JTable FuncListadoTable;
    private JTextField DescBusqTF;
    private JButton buscarButton1;
    private JButton imprimirButton1;
    private JTextField DescTF;
    private JButton guardarButton1;
    private JButton borrarButton1;
    private JButton limpiarButton1;
    private JLabel BusquedaLabel1;
    private JLabel DescripcionBusquedaLabel;
    private JLabel CategoriaLabel;
    private JLabel ID1;
    private JTextField IDTF1;
    private JLabel Descripcion;
    private JLabel ListadoLabel1;
    private JTable CatListadoTable;
    private JComboBox CatFiltrocomboBox;
    private JTextField DescripcionFiltroTF;
    private JButton buscarButton2;
    private JButton imprimirButton2;
    private JButton guardarButton2;
    private JButton borrarButton2;
    private JButton limpiarButton2;
    private JTable table1;
    private JLabel FiltroLabel;
    private JLabel CatFiltroLabel;
    private JLabel DescripcionFiltroLabel;
    private JLabel Recursolabel;
    private JLabel ID2;
    private JTextField IDTF2;
    private JComboBox CatcomboBox;
    private JTextField DescRecTF;
    private JLabel CategoriaLabelRec;
    private JLabel DescRecLabel;
    private JLabel ListadoLabel2;
    private JScrollPane RecListadoTable;
}
